### ISSUE TITLE
Windows 10 + USB Blaster Driver Issue

### ISSUE THREAD

**Issue by cojomojo** [cojomojo/ECPE071#1]
On Windows 10, the USB Blaster device driver seemingly doesn't get installed. One symptom of this is the lack of the "USB-‐Blaster [USB-‐0]" option in the _Tools>Progammer>Hardware Setup_ section of Quartus.

**Comment by cojomojo** [comment]
This issue can be fixed by doing the following:

1) Plug the DE2 dev board in to your computer.
2) Go to Device Manager in Windows
3) Find the "USB Blaster" device, it probably has a yellow exclamation next to it.
4) Right click the device and click "Properties"
5) Click "Update Driver"
6) Click "Browse My Computer for Driver Software"
7) Enter the path to the Altera installation folder
8) Hit Enter
9) Wait for successful installation.

The device should now be recognized and work.

**Comment by nicolasrosa** [comment]
What if that does not fix it? I'm trying to use the Quartus II 11.0sp1 64-bit on Windows 10. Since the usb-blaster drivers from this version doesn't work, I installed the drivers from 13.0 version. However, I still can't get working the "USB-‐Blaster [USB-‐0]" on the JTAG Programmer.

**Comment by cojomojo** [comment]
Have you tried a new version of Quartus itself to see if it works? I honestly never ran into any other issue than the one I described here and I don't currently work wtih Quartus.
